services:
  motion:
    build:
      context: .
      args:
        MOTION_ARCH: arm64
    image: easypi/motion-arm64
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./data/etc/motion.conf:/etc/motion/motion.conf
      - ./data/var:/var/lib/motion
      - /etc/localtime:/etc/localtime
    devices:
      - /dev/video0:/dev/video0
    restart: unless-stopped
