version: "3.8"

services:

  maltrail-server:
    image: vimagick/maltrail
    command: ./server.py -c etc/maltrail.conf
    volumes:
      - ./data/etc:/opt/maltrail/etc
      - ./data/server/log:/opt/maltrail/log
    network_mode: host
    restart: unless-stopped

  maltrail-sensor:
    image: vimagick/maltrail
    command: ./sensor.py -c etc/maltrail.conf
    volumes:
      - ./data/etc:/opt/maltrail/etc
      - ./data/sensor/log:/opt/maltrail/log
    network_mode: host
    depends_on:
      - maltrail-server
    restart: unless-stopped
