version: "3.8"

services:

  mitmproxy:
    image: mitmproxy/mitmproxy
    command: mitmweb --web-host 0.0.0.0
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./data:/home/mitmproxy/.mitmproxy
    restart: unless-stopped

  mitmdump:
    image: mitmproxy/mitmproxy
    command: mitmdump --mode reverse:https://httpbin.org:443@8443
    ports:
      - "8443:8443"
    volumes:
      - ./data:/home/mitmproxy/.mitmproxy
    restart: unless-stopped
