version: "3.8"
services:
  owncast:
    image: owncast/owncast:0.2.1
    command: /app/owncast
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
