#
# See: https://screego.net/#/config
#

version: "3.8"
services:
  screego:
    image: screego/server:1.10.2
    ports:
      - "5050:5050"
      - "3478:3478"
      - "50000-50200:50000-50200/udp"
    environment:
      - SCREEGO_EXTERNAL_IP=192.168.178.2
      - SCREEGO_SECRET=b8a8e200-0560-4cd5-bf10-d5426bc5e8e3
      - SCREEGO_SERVER_ADDRESS=0.0.0.0:5050
      - SCREEGO_TURN_ADDRESS=0.0.0.0:3478
      - SCREEGO_TURN_PORT_RANGE=50000:50200
    restart: unless-stopped
