services:

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    command: --config /app/config.yaml --detailed_debug
    ports:
    - "4000:4000"
    volumes:
    - ./data/litellm/config.yaml:/app/config.yaml
    environment:
    - DATABASE_URL=postgresql://litellm:litellm@postgres:5432/litellm
    - STORE_MODEL_IN_DB=True
    depends_on:
    - postgres
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=litellm
    - POSTGRES_PASSWORD=litellm
    - POSTGRES_DB=litellm
    restart: unless-stopped
