services:
  go2rtc:
    image: alexxit/go2rtc:1.9.9
    ports:
      - "1984:1984"
      - "8554:8554"
      - "8555:8555"
    volumes:
      - ./data:/config
    environment:
      - TZ=Asia/Shanghai
    devices:
      - /dev/video0
    restart: unless
