version: "3.8"
services:
  gotify:
    image: gotify/server:2.5
    ports:
      - "8080:80"
    volumes:
      - ./data:/app/data
    environment:
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=secret
      - TZ=Asia/Shanghai
    restart: unless-stopped
