version: "3.8"
services:
  flashmq:
    image: vimagick/flashmq
    ports:
      - "1883:1883"
    volumes:
      - ./data/etc:/etc/flashmq
      - ./data/log:/var/log/flashmq
      - ./data/var:/var/lib/flashmq
    restart: unless-stopped
