version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts-alpine-jdk21
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Dhudson.footerURL=http://jenkins.easypi.duckdns.org
    restart: unless-stopped
