#
# Doc: https://docs.datarhei.com/restreamer/installing/raspberry-pi-arm
#

version: "3.8"
services:
  restreamer:
    image: datarhei/restreamer:rpi-latest
    ports:
      - "1935:1935"     # RTMP
      - "8080:8080"     # WEB
      - "6000:6000/udp" # SRT
    volumes:
      - ./data/etc:/core/config
      - ./data/var:/core/data
    privileged: true
    restart: unless-stopped
