version: "3.8"
services:
  restreamer:
    image: datarhei/restreamer:rpi-latest
    ports:
      - "1935:1935"
      - "8080:8080"
      - "6000:6000/udp"
    volumes:
      - ./data/config:/core/config
      - ./data/data:/core/data
    privileged: true
    restart: unless-stopped
