#
# See: https://memgraph.com/docs/configuration/configuration-settings
#

version: "3.8"

services:

  memgraph:
    image: memgraph/memgraph-mage:1.14.1-memgraph-2.14.1
    ports:
      - "7444:7444" # Log
      - "7687:7687" # Bolt
    volumes:
      # ./data/etc:/etc/memgraph
      - ./data/log:/var/log/memgraph
      - ./data/var:/var/lib/memgraph
    environment:
      - MEMGRAPH=--telemetry-enabled=false
    restart: unless-stopped

  lab:
    image: memgraph/lab:2.11.1
    ports:
      - "3000:3000" # Web
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
    depends_on:
      - memgraph
    restart: unless-stopped
