services:
  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    command: ["--config", "/app/etc/config.json", "--api-key", "top-secret"]
    ports:
    - "8000:8000"
    volumes:
    - ./data:/app/etc
    restart: unless-stopped
