services:
  v4l2rtspserver:
    image: mpromonet/v4l2rtspserver:v0.3.11
    command: -v -c -P554 -G960x540x15 -ulive /dev/video0
    ports:
      - "554:554"
    devices:
      - /dev/video0
    privileged: true
    restart: unless-stopped
