services:
  bettercap:
    image: bettercap/bettercap
    entrypoint: sleep
    command: infinity
    volumes:
    - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    environment:
    - TZ=Asia/Shanghai
    network_mode: host
    privileged: true
    tty: true
    restart: unless-stopped
