version: "3.8"

services:

  redpanda:
    image: redpandadata/redpanda:v24.2.7
    ports:
    - "8081:8081"
    - "8082:8082"
    - "9092:9092"
    - "9644:9644"
    - "33145:33145"
    volumes:
    - ./data/etc:/etc/redpanda
    - ./data/var:/var/lib/redpanda
    restart: unless-stopped

  console:
    image: redpandadata/console:v2.7.2
    ports:
    - "8080:8080"
    volumes:
    - ./data/etc:/etc/redpanda
    depends_on:
    - redpanda
    restart: unless-stopped

  connect:
    image: redpandadata/connect:4.38.0
    command:
    - run
    - input.type=http_server
    - output.type=kafka
    - output.kafka.addresses=redpanda:9092
    - output.kafka.topic=test
    ports:
    - "4195:4195"
    depends_on:
    - redpanda
    restart: unless-stopped
