#
# See: https://esphome.io/guides/getting_started_command_line.html
#

version: "3.8"
services:
  esphome:
    image: esphome/esphome:stable
    ports:
      - "6052:6052"
    volumes:
      - ./data:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USERNAME=admin
      - PASSWORD=admin
      - ESPHOME_DASHBOARD_USE_PING=true
    ### FOR THE FIRST-TIME ONLY ###
    #devices:                     #
    #  - /dev/ttyACM0             #
    ###############################
    restart: unless-stopped
