#
# See: https://www.zigbee2mqtt.io/guide/installation/02_docker.html#docker-compose
#

version: "3.8"
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:2.1.1
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Asia/Shanghai
    devices:
      - /dev/serial/by-id/usb-Texas_Instruments_XXXXXX:/dev/ttyACM0
    group_add:
      - dialout
    user: "1000:1000"
    restart: unless-stopped
