services:

  searxng:
    image: docker.io/searxng/searxng:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://searxng.easypi.duckdns.org/
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
